### PR TITLE
Add compiler deps

### PR DESCRIPTION
**Pull request by elcritch**

### CODE REVIEW

**Comment by elcritch** [comment]
This unfortunately doesn't appear to resolve the issue. :/ 

It seems that with Nimble v0.14.2+ that the compiler package has been renamed. Cool except it also doesn't appear to find the compiler package and pass it properly anymore. There's no way to specify the compiler with the new package name. 🤷 😮‍💨 

See https://github.com/nim-lang/Nim/issues/21546 and https://github.com/nim-lang/Nim/issues/21545 .

Alas, gonna have to stick to 1.6.10 for a while.

**Comment by beef331** [comment]
Yep, regardless I'm never going to accept `requires "compiler ..."` as it  does not use the compiler api of the version you use. Passing `--path:"$nim"` still is the only good way to use the compiler api.

**Comment by elcritch** [comment]
> Yep, regardless I'm never going to accept requires "compiler ..." as it does not use the compiler api of the version you use. Passing --path:"$nim" still is the only good way to use the compiler api. 

That make sense, though it does sorta break using it with Nimble. I'd completely missed the `--path:"$nim"` piece as well.

**Comment by beef331** [comment]
It sucks, but there is no way for Nimble/Nim to load the config from a dependency(for good reason), so it is what it is sadly.

**Comment by elcritch** [comment]
Yah that makes sense, if a bit annoying. The compiler package worked with the older Nimble too, so I'd completely missed the bit about the path configs the first time. 

But thanks, the path option will let me move to the 2.0-rc! Well once I update ants with a proper config.nims.

**Pull request closed without merging**
